export enum ECategory {
    Beauty = "beauty",
    Fragrances = "fragrances",
    Furniture = "furniture",
    Groceries = "groceries",
    HomeDecoration = "home-decoration",
    KitchenAccessories = "kitchen-accessories",
    Laptops = "laptops",
    MensShirts = "mens-shirts",
    MensShoes = "mens-shoes",
    MensWatches = "mens-watches",
    MobileAccessories = "mobile-accessories",
    Motorcycle = "motorcycle",
    SkinCare = "skin-care",
    Smartphones = "smartphones",
    SportsAccessories = "sports-accessories",
    Sunglasses = "sunglasses",
    Tablets = "tablets",
    Tops = "tops",
    Vehicle = "vehicle",
    WomensBags = "womens-bags",
    WomensDresses = "womens-dresses",
    WomensJewellery = "womens-jewellery",
    WomensShoes = "womens-shoes",
    WomensWatches = "womens-watches"
}